"""
Sitemaps for Eterflame Works.
Auto-generated by Django sitemap framework — covers all main pages
and dynamic content (poems, blog posts, case studies, songs).
"""
from django.contrib.sitemaps import Sitemap
from django.urls import reverse


class StaticViewSitemap(Sitemap):
    """Static pages with no model: home, about, works divisions, etc."""
    priority = 0.8
    changefreq = "monthly"
    protocol = "https"

    def items(self):
        return [
            'works:works_home',
            'works:resources',
            'works:contact',
            'about',
            'design:design_home',
            'media:media_home',
            'studio:studio_home',
            'aythnyk:aythnyk_home',
            'aythnyk:aythnyk_tools',
            'poetry:poem_list',
            'songs:song_list',
            'blog:bloghome',
            'shop:shop_home',
        ]

    def location(self, item):
        return reverse(item)


class PoemSitemap(Sitemap):
    """All published poems."""
    changefreq = "monthly"
    priority = 0.6
    protocol = "https"

    def items(self):
        from poetry.models import Poem
        return Poem.objects.all()


class CaseStudySitemap(Sitemap):
    """All published case studies."""
    changefreq = "monthly"
    priority = 0.7
    protocol = "https"

    def items(self):
        from design_app.models import CaseStudy
        return CaseStudy.objects.filter(is_published=True)


class BlogPostSitemap(Sitemap):
    """All published blog posts."""
    changefreq = "weekly"
    priority = 0.6
    protocol = "https"

    def items(self):
        from blog.models import Post
        return Post.objects.filter(status=1)  # status=1 means Published

    def lastmod(self, obj):
        return obj.updated_on


class SongSitemap(Sitemap):
    """All songs."""
    changefreq = "monthly"
    priority = 0.5
    protocol = "https"

    def items(self):
        from songs.models import Song
        return Song.objects.all()


# Dictionary used in urls.py
sitemaps = {
    'static': StaticViewSitemap,
    'poems': PoemSitemap,
    'case_studies': CaseStudySitemap,
    'blog': BlogPostSitemap,
    'songs': SongSitemap,
}
