# Generated by Django 5.2.7 on 2026-08-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("poetry", "0010_poem_is_free_lead_magnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="editorial_author",
            field=models.ForeignKey(
                blank=True,
                help_text="Nombre público que verá el lector. Si se deja vacío, muestra 'Eterflame'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to="poetry.author",
            ),
        ),
    ]
