# Generated by Django 5.2.7 on 2026-04-24 13:32

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("poetry", "0008_alter_author_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("lyrics", models.TextField(blank=True)),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("emotional", "Emotional Series"),
                            ("lyric", "Lyric Series"),
                            ("dramatic", "Dramatic Series"),
                            ("cinematic", "Cinematic Series"),
                        ],
                        max_length=20,
                    ),
                ),
                ("suno_url", models.URLField(blank=True, help_text="Suno embed URL")),
                ("spotify_url", models.URLField(blank=True)),
                ("apple_music_url", models.URLField(blank=True)),
                ("pandora_url", models.URLField(blank=True)),
                ("youtube_music_url", models.URLField(blank=True)),
                (
                    "cover_image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "pdf_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in USD for PDF download",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "pdf_buy_url",
                    models.URLField(
                        blank=True, help_text="Payment link (Gumroad, Stripe, etc)"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "poem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs",
                        to="poetry.poem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
