# Generated by Django 5.2.7 on 2026-04-24 14:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="facebook_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Facebook reel thumbnail",
                max_length=255,
                verbose_name="facebook_thumb",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="facebook_url",
            field=models.URLField(blank=True, help_text="Facebook reel URL"),
        ),
        migrations.AddField(
            model_name="song",
            name="instagram_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Instagram reel thumbnail",
                max_length=255,
                verbose_name="instagram_thumb",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="instagram_url",
            field=models.URLField(blank=True, help_text="Instagram reel URL"),
        ),
        migrations.AddField(
            model_name="song",
            name="tiktok_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="TikTok hook thumbnail",
                max_length=255,
                verbose_name="tiktok_thumb",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="tiktok_url",
            field=models.URLField(blank=True, help_text="TikTok hook URL"),
        ),
        migrations.AddField(
            model_name="song",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL (poem image + voice + music) — shown on page",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="suno_url",
            field=models.URLField(
                blank=True, help_text="Internal use only — not shown publicly"
            ),
        ),
    ]
