# Generated by Django 5.2.7 on 2026-04-24 14:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_facebook_thumbnail_song_facebook_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="facebook_thumbnail",
        ),
        migrations.RemoveField(
            model_name="song",
            name="instagram_thumbnail",
        ),
        migrations.RemoveField(
            model_name="song",
            name="tiktok_thumbnail",
        ),
        migrations.AddField(
            model_name="song",
            name="reel_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Shared thumbnail for all social hooks (Instagram, TikTok, Facebook)",
                max_length=255,
                verbose_name="reel_thumb",
            ),
        ),
    ]
