# Generated by Django 5.2.7 on 2026-08-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_remove_song_facebook_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="catalog_number",
            field=models.CharField(
                blank=True,
                help_text="Número de catálogo del sello, ej. EFM-001",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="release_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha real de lanzamiento en DistroKid",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="release_type",
            field=models.CharField(
                choices=[("single", "Single"), ("ep", "EP"), ("album", "Álbum")],
                default="single",
                max_length=10,
            ),
        ),
    ]
