# Generated by Django 5.2.7 on 2026-08-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_song_catalog_number_song_release_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="upc",
            field=models.CharField(
                blank=True,
                help_text="UPC del lanzamiento (DistroKid) — uso interno",
                max_length=20,
            ),
        ),
    ]
