# Generated by Django 5.2.7 on 2026-08-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_song_upc"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="bmi_work_number",
            field=models.CharField(
                blank=True, help_text="Número de obra en BMI", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="isrc",
            field=models.CharField(
                blank=True, help_text="ISRC — identifica la GRABACIÓN", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="iswc",
            field=models.CharField(
                blank=True,
                help_text="ISWC — identifica la COMPOSICIÓN (no cambia al regrabar)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="safe_creative_id",
            field=models.CharField(
                blank=True,
                help_text="Certificado Safe Creative + fecha de emisión",
                max_length=60,
            ),
        ),
    ]
