# Generated by Django 5.2.7 on 2026-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0006_song_bmi_work_number_song_isrc_song_iswc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="iswc",
            new_name="bmi_iswc",
        ),
        migrations.AlterField(
            model_name="song",
            name="isrc",
            field=models.CharField(
                blank=True,
                help_text="ISRC — identifica la GRABACIÓN (DistroKid)",
                max_length=20,
            ),
        ),
    ]
