# Generated by Django 5.2.7 on 2026-05-04 15:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kicker",
                    models.CharField(
                        help_text="e.g. 'Featured Project', 'Web', 'Data · ML'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated e.g. Python,Scikit-learn",
                        max_length=300,
                    ),
                ),
                (
                    "is_screenshot",
                    models.BooleanField(
                        default=False,
                        help_text="Use contain layout instead of cover (for screenshots/dashboards)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
