# Generated by Django 5.2.7 on 2026-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_app", "0002_seed_portfolio_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioitem",
            name="image",
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Paste the full Cloudinary URL or any image URL",
            ),
        ),
    ]
