# Generated by Django 5.2.7 on 2026-05-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_app", "0003_remove_portfolioitem_image_portfolioitem_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "eyebrow",
                    models.CharField(
                        default="Case Study",
                        help_text="e.g. 'Data · ML · Case Study'",
                        max_length=200,
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("live_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("metric_1_value", models.CharField(blank=True, max_length=50)),
                ("metric_1_label", models.CharField(blank=True, max_length=100)),
                ("metric_2_value", models.CharField(blank=True, max_length=50)),
                ("metric_2_label", models.CharField(blank=True, max_length=100)),
                ("metric_3_value", models.CharField(blank=True, max_length=50)),
                ("metric_3_label", models.CharField(blank=True, max_length=100)),
                ("metric_4_value", models.CharField(blank=True, max_length=50)),
                ("metric_4_label", models.CharField(blank=True, max_length=100)),
                ("metric_5_value", models.CharField(blank=True, max_length=50)),
                ("metric_5_label", models.CharField(blank=True, max_length=100)),
                ("challenge", models.TextField(blank=True)),
                ("approach", models.TextField(blank=True)),
                (
                    "approach_bullets",
                    models.TextField(blank=True, help_text="One bullet per line"),
                ),
                (
                    "approach_insight",
                    models.TextField(blank=True, help_text="Highlighted insight block"),
                ),
                (
                    "deliverables",
                    models.TextField(blank=True, help_text="One bullet per line"),
                ),
                ("results_intro", models.TextField(blank=True)),
                ("results_outro", models.TextField(blank=True)),
                (
                    "cta_title",
                    models.CharField(
                        default="Let's turn your data into direction.", max_length=200
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_study",
                        to="design_app.portfolioitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
            },
        ),
    ]
