# Generated by Django 5.2.7 on 2026-05-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_app", "0005_casestudy_result_1_desc_casestudy_result_2_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="title_line1",
            field=models.CharField(
                blank=True,
                help_text="First line of hero title e.g. 'Digital Marketing'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="title_line2",
            field=models.CharField(
                blank=True,
                help_text="Second line in italic cyan e.g. 'Conversion Predictor'",
                max_length=200,
            ),
        ),
    ]
