# Generated by Django 5.2.7 on 2026-05-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design_app", "0006_casestudy_title_line1_casestudy_title_line2"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Highlight this project as the main featured work (renders full-width)",
            ),
        ),
    ]
