# Generated by Django 5.2.7 on 2026-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommissionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("wedding", "Wedding"),
                            ("birthday", "Birthday"),
                            ("memorial", "Memorial / Loss"),
                            ("dedication", "Dedication"),
                            ("anniversary", "Anniversary"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(max_length=200)),
                ("details", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Español"),
                            ("both", "Both"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("budget", models.CharField(blank=True, max_length=50)),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_on"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("print", "Prints & Art"),
                            ("digital", "Digital Downloads"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="shop/products/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-featured", "-created_on"],
            },
        ),
    ]
