# Generated by Django 5.2.7 on 2026-05-14 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("footer", "Footer (todas las páginas)"),
                            ("aythnyk_section", "Sección /aythnyk/"),
                            ("blog", "Form del blog"),
                            ("user_optin", "Opt-in al registrarse"),
                            ("import", "Importado manualmente"),
                        ],
                        default="footer",
                        max_length=32,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, help_text="Reservado para double opt-in futuro"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Suscriptor",
                "verbose_name_plural": "Suscriptores",
                "ordering": ["-created_at"],
            },
        ),
    ]
