# Generated by Django 5.2.7 on 2026-05-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audience", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="source",
            field=models.CharField(
                choices=[
                    ("footer", "Footer (todas las páginas)"),
                    ("aythnyk_section", "Sección /aythnyk/"),
                    ("blog", "Form del blog"),
                    ("user_optin", "Opt-in al registrarse"),
                    ("import", "Importado manualmente"),
                    ("lead_magnet_poem", "Lead magnet — Free poem PDF"),
                ],
                default="footer",
                max_length=32,
            ),
        ),
    ]
