# Generated by Django 5.2.7 on 2026-04-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_about_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="credential_subtitle",
            field=models.CharField(
                blank=True,
                default="Skills · Focus Areas · Technical Direction",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="credential_summary",
            field=models.TextField(
                blank=True,
                default="A curated overview of this profile’s strongest technical, creative, and strategic capabilities.",
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="credential_title",
            field=models.CharField(
                blank=True, default="Core Expertise", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="focus_1_text",
            field=models.CharField(
                blank=True,
                default="Responsive layouts, UI systems, and user experience foundations.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="focus_1_title",
            field=models.CharField(blank=True, default="Frontend", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="focus_2_text",
            field=models.CharField(
                blank=True,
                default="Django architecture, databases, APIs, and scalable web logic.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="focus_2_title",
            field=models.CharField(blank=True, default="Backend", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="focus_3_text",
            field=models.CharField(
                blank=True,
                default="Analytics, visualisation, and machine learning workflows.",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="focus_3_title",
            field=models.CharField(blank=True, default="Data", max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="skills",
            field=models.CharField(
                blank=True,
                help_text="Separate skills with commas. Example: Python, Django, JavaScript, PostgreSQL",
                max_length=500,
            ),
        ),
    ]
