# Generated by Django 5.2.7 on 2026-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_about_credential_subtitle_about_credential_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="skill_category_1_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="about",
            name="skill_category_1_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="about",
            name="skill_category_2_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="about",
            name="skill_category_2_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="about",
            name="skill_category_3_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="about",
            name="skill_category_3_title",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
