# Generated by Django 5.2.7 on 2026-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_about_skill_category_1_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
