# Generated by Django 5.2.7 on 2026-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0008_alter_author_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="likes_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Public anonymous likes (global counter, browser anti-spam)",
            ),
        ),
    ]
