# Generated by Django 5.2.7 on 2026-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0009_poem_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="is_free_lead_magnet",
            field=models.BooleanField(
                default=False,
                help_text="When True, this poem is offered as free downloadable PDF in exchange for email at /aythnyk/free-poem/. If multiple poems are marked, the most-liked is shown first.",
            ),
        ),
    ]
