# Generated by Django 5.2.7 on 2026-05-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("design", "EF Design"),
                            ("media", "EF Media"),
                            ("studio", "EF Studio"),
                        ],
                        help_text="Which Eterflame division this testimonial belongs to",
                        max_length=10,
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="The testimonial text (will appear in quotes)"
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                (
                    "author_role",
                    models.CharField(
                        help_text="e.g. 'Founder, Acme Corp' or 'Marketing Director'",
                        max_length=200,
                    ),
                ),
                ("author_company", models.CharField(blank=True, max_length=200)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this testimonial in division page",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower = first. Same order = newest first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
