# Generated by Django 5.2.7 on 2026-04-24 14:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, verbose_name="logo"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        help_text="One line: what it does", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="2-3 sentences. B2B: professional tone. Aythnyk: personal/creative tone."
                    ),
                ),
                ("affiliate_url", models.URLField(help_text="Your affiliate link")),
                (
                    "commission",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '22% recurrente x 12 meses'",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dev", "Development"),
                            ("design", "Design"),
                            ("hosting", "Hosting"),
                            ("music", "Music & Distribution"),
                            ("voice", "Voice & Audio AI"),
                            ("video", "Video & Editing"),
                            ("marketing", "Marketing"),
                            ("org", "Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("b2b", "Etherflame Works only"),
                            ("aythnyk", "Aythnyk only"),
                            ("both", "Both sections"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
