# Generated by Django 5.2.7 on 2026-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliatelink",
            name="simpleicons_slug",
            field=models.CharField(
                blank=True,
                help_text="Simple Icons slug e.g. 'canva', 'notion', 'framer'",
                max_length=100,
            ),
        ),
    ]
