# Generated by Django 5.2.7 on 2026-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_seed_simpleicons_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatelink",
            name="channel",
            field=models.CharField(
                choices=[
                    ("b2b", "Eterflame Works only"),
                    ("aythnyk", "Aythnyk only"),
                    ("both", "Both sections"),
                ],
                default="both",
                max_length=10,
            ),
        ),
    ]
